o'brien	/oʊˈbɹaɪɪn/
o'leary	/oʊˈɫɪɹi/
o'neal	/oʊˈniɫ/
o'reilly	/oʊˈɹaɪɫi/
oases	/oʊˈeɪsiz/
oasis	/oʊˈeɪsɪs/
obedience	/oʊˈbidiəns/
obedient	/oʊˈbidiənt/
obediently	/oʊˈbidiəntɫi/, /oʊˈbidjəntɫi/
obey	/oʊˈbeɪ/
obeyed	/oʊˈbeɪd/
obeying	/oʊˈbeɪɪŋ/
obeys	/oʊˈbeɪz/
obituaries	/oʊˈbɪtʃuˌɛɹiz/
obituary	/oʊˈbɪtʃuˌɛɹi/
ohio	/oʊˈhaɪoʊ/
ohio's	/oʊˈhaɪoʊz/
olfactory	/oʊɫˈfæktɝi/
oligopolistic	/oʊˌɫɪɡəpoʊˈɫɪstɪk/
<!-- olivia	/oʊˈɫɪviə/ -->
<!-- olivia's	/oʊˈɫɪviəz/ -->
<!-- olympia	/oʊˈɫɪmpiə/ -->
<!-- olympia's	/oʊˈɫɪmpiəz/ -->
<!-- olympiad	/oʊˈɫɪmpiˌæd/ -->
<!-- olympiads	/oʊˈɫɪmpiˌæd/ -->
<!-- olympian	/oʊˈɫɪmpiən/ -->
<!-- olympians	/oʊˈɫɪmpiənz/ -->
<!-- olympias	/oʊˈɫɪmpiəs/ -->
<!-- olympic	/oʊˈɫɪmpɪk/ -->
<!-- olympic's	/oʊˈɫɪmpɪks/ -->
<!-- olympics	/oʊˈɫɪmpɪks/ -->
<!-- olympics'	/oʊˈɫɪmpɪks/ -->
<!-- olympus	/oʊˈɫɪmpəs/ -->
<!-- olympus'	/oʊˈɫɪmpəs/ -->
oman	/oʊˈmɑn/
omega	/oʊˈmeɪɡə/, /oʊˈmɛɡə/
omission	/oʊˈmɪʃən/
omissions	/oʊˈmɪʃənz/
omit	/oʊˈmɪt/
omits	/oʊˈmɪts/
omitted	/oʊˈmɪtəd/, /oʊˈmɪtɪd/
omitting	/oʊˈmɪtɪŋ/
opine	/oʊˈpaɪn/
opined	/oʊˈpaɪnd/
opines	/oʊˈpaɪnz/
opining	/oʊˈpaɪnɪŋ/
opossum	/oʊˈpɑsəm/
orion	/oʊˈɹaɪən/, /ɔˈɹaɪən/
orion's	/oʊˈɹaɪənz/, /ɔˈɹaɪənz/
osake	/oʊˈsɑki/
ovarian	/oʊˈvɛˌɹiən/
ovation	/oʊˈveɪʃən/
ovations	/oʊˈveɪʃənz/
overate	/oʊvɝˈeɪt/
overhung	/oʊvɝˈhəŋ/
oversimplification	/oʊvɝˈsɪmpɫɪfɪˌkeɪʃən/
oversimplified	/oʊvɝˈsɪmpɫɪˌfaɪd/
oversimplify	/oʊvɝˈsɪmpɫɪˌfaɪ/
oversimplifying	/oʊvɝˈsɪmpɫɪˌfaɪɪŋ/
overtly	/oʊˈvɝtɫi/
overtrain	/oʊvɝˈtɹeɪn/
overtraining	/oʊvɝˈtɹeɪnɪŋ/

<!-- aux	/ˈoʊ/ -->
oak	/ˈoʊk/
oak's	/ˈoʊks/
oakdale	/ˈoʊkˌdeɪɫ/
oakland	/ˈoʊkɫənd/
oakland's	/ˈoʊkɫəndz/
oakleaf	/ˈoʊˌkɫif/
oakley	/ˈoʊkɫi/
oakley's	/ˈoʊkɫiz/
oakmont	/ˈoʊkˌmɑnt/
oakridge	/ˈoʊˌkɹɪdʒ/
oaks	/ˈoʊks/
oaks'	/ˈoʊks/
oakville	/ˈoʊkˌvɪɫ/
oakwood	/ˈoʊˌkwʊd/
oat	/ˈoʊt/
oates	/ˈoʊts/
oath	/ˈoʊθ/
oaths	/ˈoʊðz/, /ˈoʊθs/
oatmeal	/ˈoʊtˌmiɫ/
oats	/ˈoʊts/
oberlin	/ˈoʊbɝɫɪn/
oboe	/ˈoʊboʊ/
oboist	/ˈoʊboʊəst/
ocean	/ˈoʊʃən/
ocean's	/ˈoʊʃənz/
oceanfront	/ˈoʊʃənˌfɹənt/
oceangoing	/ˈoʊʃənˌɡoʊɪŋ/
oceans	/ˈoʊʃənz/
oceanside	/ˈoʊʃənˌsaɪd/
oceanview	/ˈoʊʃənˌvju/
odious	/ˈoʊdiəs/
odor	/ˈoʊdɝ/
odorant	/ˈoʊdɝənt/
odorless	/ˈoʊdɝɫəs/
odorous	/ˈoʊdɝəs/
odors	/ˈoʊdɝz/
odour	/ˈoʊdɝ/
odours	/ˈoʊdɝs/
ogre	/ˈoʊɡɝ/
ogress	/ˈoʊɡɹəs/
oh	/ˈoʊ/
ohm	/ˈoʊm/
ohm's	/ˈoʊmz/
ohms	/ˈoʊmz/
okey	/ˈoʊki/
okey-dokey	/ˈoʊkiˈdoʊki/
oki	/ˈoʊki/
okie	/ˈoʊki/
okra	/ˈoʊkɹə/
olaf	/ˈoʊɫɑf/
old	/ˈoʊɫd/
old's	/ˈoʊɫdz/
olden	/ˈoʊɫdən/
older	/ˈoʊɫdɝ/
oldest	/ˈoʊɫdəst/
oldie	/ˈoʊɫdi/
oldies	/ˈoʊɫdiz/
oligarch	/ˈoʊɫɪˌɡɑɹk/
oligarchs	/ˈoʊɫɪˌɡɑɹks/
olin	/ˈoʊɫɪn/
olin's	/ˈoʊɫɪnz/
olsen	/ˈoʊɫsən/
olsen's	/ˈoʊɫsənz/
omaha	/ˈoʊməˌhɑ/
omaha's	/ˈoʊməˌhɑz/
omar	/ˈoʊmɑɹ/
omen	/ˈoʊmən/
omens	/ˈoʊmənz/
onerous	/ˈoʊnɝəs/
only	/ˈoʊnɫi/
ono	/ˈoʊnoʊ/
onus	/ˈoʊnəs/
opal	/ˈoʊpəɫ/
opal's	/ˈoʊpəɫz/
open	/ˈoʊpən/
open-ended	/ˈoʊpəˌnɛndəd/
open-source	/ˈoʊpənˌsɔɹs/
opened	/ˈoʊpənd/
opener	/ˈoʊpənɝ/
openers	/ˈoʊpənɝz/
opening	/ˈoʊpənɪŋ/
openings	/ˈoʊpənɪŋz/
openly	/ˈoʊpənɫi/
openness	/ˈoʊpənəs/, /ˈoʊpənnəs/
opens	/ˈoʊpənz/
openwork	/ˈoʊpənˌwɝk/
opiate	/ˈoʊˌpiət/
opiates	/ˈoʊˌpiəts/
opium	/ˈoʊpiəm/
oprah	/ˈoʊpɹə/
oprah's	/ˈoʊpɹəz/
otis	/ˈoʊtɪs/
oval	/ˈoʊvəɫ/
ovaries	/ˈoʊˌvɝiz/
ovary	/ˈoʊˌvɝi/
over	/ˈoʊvɝ/
overabundance	/ˈoʊvɝəˈbəndəns/
overall	/ˈoʊvɝˌɔɫ/
overalls	/ˈoʊvɝˌɔɫz/
overambitious	/ˈoʊvɝæmˌbɪʃəs/
overarching	/ˈoʊvɝˌɑɹtʃɪŋ/
overbearing	/ˈoʊvɝˈbɛɹɪŋ/
overbilled	/ˈoʊvɝˌbɪɫd/
overbilling	/ˈoʊvɝˌbɪɫɪŋ/
overboard	/ˈoʊvɝˌbɔɹd/
overbook	/ˈoʊvɝˌbʊk/
overbooked	/ˈoʊvɝˌbʊkt/
overbooking	/ˈoʊvɝˌbʊkɪŋ/
overbooks	/ˈoʊvɝˌbʊks/
overbought	/ˈoʊvɝˈbɔt/
overbuilding	/ˈoʊvɝˌbɪɫdɪŋ/
overbuilt	/ˈoʊvɝˈbɪɫt/
overburden	/ˈoʊvɝˈbɝdən/
overburdened	/ˈoʊvɝˈbɝdənd/
overcame	/ˈoʊvɝˈkeɪm/
overcapacity	/ˈoʊvɝkəˈpæsəti/
overcast	/ˈoʊvɝˌkæst/
overcharge	/ˈoʊvɝˌtʃɑɹdʒ/
overcharged	/ˈoʊvɝˈtʃɑɹdʒd/
overcharges	/ˈoʊvɝˌtʃɑɹdʒɪz/
overclock	/ˈoʊvɝˈkɫɔk/
overclocking	/ˈoʊvɝˈkɫɔkɪŋ/
overcoat	/ˈoʊvɝˌkoʊt/
overcoats	/ˈoʊvɝˌkoʊts/
overcome	/ˈoʊvɝˌkəm/
overcomes	/ˈoʊvɝˌkəmz/
overcoming	/ˈoʊvɝˌkəmɪŋ/
overconsumption	/ˈoʊvɝkənˌsəmpʃən/
overcrowded	/ˈoʊvɝˌkɹaʊdɪd/
overcrowding	/ˈoʊvɝˌkɹaʊdɪŋ/
overdependence	/ˈoʊvɝdɪˌpɛndəns/
overdependent	/ˈoʊvɝdɪˌpɛndənt/
overdid	/ˈoʊvɝˌdɪd/
overdo	/ˈoʊvɝˈdu/
overdoing	/ˈoʊvɝˈduɪŋ/
overdone	/ˈoʊvɝˈdən/
overdose	/ˈoʊvɝˌdoʊs/
overdosed	/ˈoʊvɝˌdoʊst/
overdoses	/ˈoʊvɝˌdoʊsɪz/
overdosing	/ˈoʊvɝˌdoʊsɪŋ/
overdraft	/ˈoʊvɝˌdɹæft/
overdrafting	/ˈoʊvɝˌdɹæftɪŋ/
overdrafts	/ˈoʊvɝˌdɹæfts/
overdraw	/ˈoʊvɝˌdɹɔ/
overdrawn	/ˈoʊvɝˈdɹɔn/
overdress	/ˈoʊvɝˌdɹɛs/
overdrew	/ˈoʊvɝˌdɹu/
overdrive	/ˈoʊvɝˌdɹaɪv/
overdue	/ˈoʊvɝˈdu/
overeager	/ˈoʊvɝˌiɡɝ/
overeat	/ˈoʊvɝˌit/
overeating	/ˈoʊvɝˈitɪŋ/
overemphasize	/ˈoʊvɝˈɛmfəˌsaɪz/
overemphasized	/ˈoʊvɝˈɛmfəˌsaɪzd/
overemphasizes	/ˈoʊvɝˈɛmfəˌsaɪzɪz/
overemphasizing	/ˈoʊvɝˈɛmfəˌsaɪzɪŋ/
overfill	/ˈoʊvɝˌfɪɫ/
overfishing	/ˈoʊvɝˌfɪʃɪŋ/
overflight	/ˈoʊvɝˌfɫaɪt/
overflights	/ˈoʊvɝˌfɫaɪts/
overflow	/ˈoʊvɝˌfɫoʊ/, /ˌoʊvɝˈfɫoʊ/
overflowing	/ˈoʊvɝˌfɫoʊɪŋ/
overflows	/ˈoʊvɝˌfɫoʊz/
overfund	/ˈoʊvɝˌfənd/
overfunded	/ˈoʊvɝˌfəndɪd/
overfunding	/ˈoʊvɝˌfəndɪŋ/
overgenerous	/ˈoʊvɝˌdʒɛnɝəs/
overgrazing	/ˈoʊvɝˌɡɹeɪzɪŋ/
overgrowth	/ˈoʊvɝɡɹoʊθ/
overhang	/ˈoʊvɝˌhæŋ/
overhanging	/ˈoʊvɝˌhæŋɪŋ/
overhangs	/ˈoʊvɝˌhæŋz/
overhaul	/ˈoʊvɝˌhɔɫ/
overhauled	/ˈoʊvɝˌhɔɫd/
overhauling	/ˈoʊvɝˌhɔɫɪŋ/
overhauls	/ˈoʊvɝˌhɔɫz/
overhead	/ˈoʊvɝˈhɛd/
overheads	/ˈoʊvɝˌhɛdz/
overhear	/ˈoʊvɝˈhiɹ/
overheard	/ˈoʊvɝˈhɝd/
overhears	/ˈoʊvɝˈhiɹz/
overheat	/ˈoʊvɝˌhit/
overheated	/ˈoʊvɝˌhitɪd/
overheating	/ˈoʊvɝˌhitɪŋ/
overheats	/ˈoʊvɝˌhits/
overkill	/ˈoʊvɝˌkɪɫ/
overlaid	/ˈoʊvɝˌɫeɪd/
overlain	/ˈoʊvɝˌɫeɪn/
overlap	/ˈoʊvɝˌɫæp/
overlapped	/ˈoʊvɝˌɫæpt/
overlapping	/ˈoʊvɝˌɫæpɪŋ/
overlaps	/ˈoʊvɝˌɫæps/
overlay	/ˈoʊvɝˌɫeɪ/
overlays	/ˈoʊvɝˌɫeɪz/
overload	/ˈoʊvɝˌɫoʊd/
overloaded	/ˈoʊvɝˌɫoʊdɪd/
overloading	/ˈoʊvɝˌɫoʊdɪŋ/
overloads	/ˈoʊvɝˌɫoʊdz/
overlook	/ˈoʊvɝˌɫʊk/
overlooked	/ˈoʊvɝˌɫʊkt/
overlooking	/ˈoʊvɝˌɫʊkɪŋ/
overlooks	/ˈoʊvɝˌɫʊks/
overlord	/ˈoʊvɝˌɫɔɹd/
overlords	/ˈoʊvɝˌɫɔɹdz/
overly	/ˈoʊvɝɫi/
overman	/ˈoʊvɝmən/
overmatched	/ˈoʊvɝˈmætʃt/
overnight	/ˈoʊvɝˈnaɪt/
overpaid	/ˈoʊvɝˈpeɪd/
overpass	/ˈoʊvɝˌpæs/
overpasses	/ˈoʊvɝˌpæsɪz/
overpay	/ˈoʊvɝˌpeɪ/
overpaying	/ˈoʊvɝˌpeɪɪŋ/
overpayment	/ˈoʊvɝˌpeɪmənt/
overpayments	/ˈoʊvɝˌpeɪmənts/
overplay	/ˈoʊvɝˈpɫeɪ/
overplayed	/ˈoʊvɝˈpɫeɪd/
overplaying	/ˈoʊvɝˈpɫeɪɪŋ/
overplays	/ˈoʊvɝˈpɫeɪz/
overpowering	/ˈoʊvɝˈpaʊɹɪŋ/
overpriced	/ˈoʊvɝˌpɹaɪst/
overproduce	/ˈoʊvɝpɹəˈdus/
overproduced	/ˈoʊvɝpɹəˈdust/
overproducer	/ˈoʊvɝpɹəˈdusɝ/
overproducers	/ˈoʊvɝpɹəˈdusɝz/
overproduction	/ˈoʊvɝpɹəˈdəkʃən/
overqualified	/ˈoʊvɝˌkwɑɫəˌfaɪd/
overqualify	/ˈoʊvɝˌkwɑɫɪˌfaɪ/
overran	/ˈoʊvɝˈɹæn/
overreach	/ˈoʊvɝˌɹitʃ/
overreached	/ˈoʊvɝˌɹitʃt/
overreaches	/ˈoʊvɝˌɹitʃɪz/
overreaching	/ˈoʊvɝˌɹitʃɪŋ/
overreact	/ˈoʊvɝɹiˈækt/
overreacted	/ˈoʊvɝɹiˌæktɪd/
overreacting	/ˈoʊvɝɹiˌæktɪŋ/
overreaction	/ˈoʊvɝɹiˌækʃən/
overreacts	/ˈoʊvɝɹiˈækts/
overregulate	/ˈoʊvɝˈɹɛɡjəˌɫeɪt/
overregulates	/ˈoʊvɝˈɹɛɡjəˌɫeɪts/
overreliance	/ˈoʊvɝɹɪˌɫaɪəns/
overrepresent	/ˈoʊvɝˌɹɛpɹəˈzɛnt/
overrepresented	/ˈoʊvɝˌɹɛpɹəˈzɛntɪd/
overridden	/ˈoʊvɝˈɹɪdən/
override	/ˈoʊvɝˌɹaɪd/
overrides	/ˈoʊvɝˌɹaɪdz/
overriding	/ˈoʊvɝˌɹaɪdɪŋ/
overripe	/ˈoʊvɝˈɹaɪp/
overrode	/ˈoʊvɝˈɹoʊd/
overrule	/ˈoʊvɝˌɹuɫ/
overrules	/ˈoʊvɝˌɹuɫz/
overruling	/ˈoʊvɝˌɹuɫɪŋ/
overrun	/ˈoʊvɝˌɹən/
overrunning	/ˈoʊvɝˌɹənɪŋ/
overruns	/ˈoʊvɝˌɹənz/
overseas	/ˈoʊvɝˈsiz/
oversee	/ˈoʊvɝˌsi/
overseeing	/ˈoʊvɝˌsiɪŋ/
overseen	/ˈoʊvɝˌsin/
overseer	/ˈoʊvɝˈsiɝ/
oversees	/ˈoʊvɝˌsiz/
oversell	/ˈoʊvɝˌsɛɫ/
overselling	/ˈoʊvɝˌsɛɫɪŋ/
overshadow	/ˈoʊvɝˈʃædoʊ/
overshadowing	/ˈoʊvɝˈʃædoʊɪŋ/
overshadows	/ˈoʊvɝˈʃædoʊz/
overshoot	/ˈoʊvɝˌʃut/
overshooting	/ˈoʊvɝˌʃutɪŋ/
overshot	/ˈoʊvɝˌʃɑt/
oversight	/ˈoʊvɝˌsaɪt/
oversized	/ˈoʊvɝˌsaɪzd/
oversold	/ˈoʊvɝˈsoʊɫd/
overspend	/ˈoʊvɝˌspɛnd/
overspending	/ˈoʊvɝˌspɛndɪŋ/
overspends	/ˈoʊvɝˌspɛndz/
overspent	/ˈoʊvɝˈspɛnt/
overstaff	/ˈoʊvɝˌstæf/
overstaffed	/ˈoʊvɝˌstæft/
overstate	/ˈoʊvɝˌsteɪt/
overstated	/ˈoʊvɝˌsteɪtɪd/
overstatement	/ˈoʊvɝˌsteɪtmənt/
overstatements	/ˈoʊvɝˌsteɪtmənts/
overstates	/ˈoʊvɝˌsteɪts/
overstating	/ˈoʊvɝˌsteɪtɪŋ/
overstep	/ˈoʊvɝˌstɛp/
overstepped	/ˈoʊvɝˌstɛpt/
overstepping	/ˈoʊvɝˌstɛpɪŋ/
overstuff	/ˈoʊvɝˌstəf/
overstuffed	/ˈoʊvɝˌstəft/
overt	/ˈoʊvɝt/, /oʊˈvɝt/
overtake	/ˈoʊvɝˌteɪk/
overtaken	/ˈoʊvɝˌteɪkən/
overtakes	/ˈoʊvɝˌteɪks/
overtaking	/ˈoʊvɝˌteɪkɪŋ/
overtax	/ˈoʊvɝˌtæks/
overthrow	/ˈoʊvɝˌθɹoʊ/
overthrowing	/ˈoʊvɝˌθɹoʊɪŋ/
overthrows	/ˈoʊvɝˌθɹoʊz/
overtime	/ˈoʊvɝˌtaɪm/
overton	/ˈoʊvɝtən/
overtone	/ˈoʊvɝˌtoʊn/
overtones	/ˈoʊvɝˌtoʊnz/
overture	/ˈoʊvɝtʃɝ/
overtures	/ˈoʊvɝˌtʃʊɹz/
overturn	/ˈoʊvɝˌtɝn/
overturned	/ˈoʊvɝˌtɝnd/
overturning	/ˈoʊvɝˌtɝnɪŋ/
overturns	/ˈoʊvɝˌtɝnz/
overvalue	/ˈoʊvɝˌvæɫju/
overvalued	/ˈoʊvɝˌvæɫjud/
overview	/ˈoʊvɝvˌju/
overviews	/ˈoʊvɝvˌjuz/
ovule	/ˈoʊvjuɫ/
ovules	/ˈoʊvjuɫz/
ovum	/ˈoʊvəm/
owe	/ˈoʊ/
owed	/ˈoʊd/
owen	/ˈoʊən/
owen's	/ˈoʊənz/
owes	/ˈoʊz/
owing	/ˈoʊɪŋ/
own	/ˈoʊn/
owned	/ˈoʊnd/
owner	/ˈoʊnɝ/
owner's	/ˈoʊnɝz/
owners	/ˈoʊnɝz/
owners'	/ˈoʊnɝz/
ownership	/ˈoʊnɝˌʃɪp/
owning	/ˈoʊnɪŋ/
owns	/ˈoʊnz/

o'shaughnessy	/ˌoʊˈʃɑnɪsi/
oahu	/ˌoʊˈɑhu/
obama	/ˌoʊˈbɑmə/
obama's	/ˌoʊˈbɑməz/
obamacare	/ˌoʊˈbɑməˌkɛɹ/
oceaneering	/ˌoʊʃəˈnɪɹɪŋ/
oceania	/ˌoʊˌʃiˈænjə/
oceanic	/ˌoʊʃiˈænɪk/
oceanographer	/ˌoʊʃəˈnɑɡɹəfɝ/
oceanographic	/ˌoʊʃənəˈɡɹæfɪk/
oceanography	/ˌoʊʃəˈnɑɡɹəfi/
odometer	/ˌoʊˈdɑmətɝ/
odometers	/ˌoʊˈdɑmətɝz/
okay	/ˌoʊˈkeɪ/
okayed	/ˌoʊˈkeɪd/
okays	/ˌoʊˈkeɪz/
okinawa	/ˌoʊˌkɪˈnɑwə/, /ˌoʊkiˈnɑˌwɑ/
oklahoma	/ˌoʊkɫəˈhoʊmə/
oklahoma's	/ˌoʊkɫəˈhoʊməz/
oklahoman	/ˌoʊkɫəˈhoʊmən/
oklahomans	/ˌoʊkɫəˈhoʊmənz/
old-fashioned	/ˌoʊɫdˈfæʃənd/
old-growth	/ˌoʊɫdˈɡɹoʊθ/
old-school	/ˌoʊɫdˈskuɫ/
old-timer	/ˌoʊɫdˈtaɪmɝ/
old-timers	/ˌoʊɫdˈtaɪmɝz/
oldfashioned	/ˌoʊɫdˈfæʃənd/
overbill	/ˌoʊvɝˈbɪɫ/
overbills	/ˌoʊvɝˈbɪɫz/
overblown	/ˌoʊvɝˈbɫoʊn/
overcharging	/ˌoʊvɝˈtʃɑɹdʒɪŋ/
overconfidence	/ˌoʊvɝˈkɑnfɪdəns/
overconfident	/ˌoʊvɝˈkɑnfɪdənt/
overcook	/ˌoʊvɝˈkʊk/
overcooked	/ˌoʊvɝˈkʊkt/
overcooking	/ˌoʊvɝˈkʊkɪŋ/
overcooks	/ˌoʊvɝˈkʊks/
overcrowd	/ˌoʊvɝˈkɹaʊd/
overcrowds	/ˌoʊvɝˈkɹaʊdz/
overdoes	/ˌoʊvɝˈdəz/
overestimate	/ˌoʊvɝˈɛstəˌmeɪt/
overestimated	/ˌoʊvɝˈɛstəˌmeɪtɪd/
overestimates	/ˌoʊvɝˈɛstəˌmeɪts/
overestimating	/ˌoʊvɝˈɛstəˌmeɪtɪŋ/
overexcite	/ˌoʊvɝɛkˈsaɪt/
overexcited	/ˌoʊvɝɛkˈsaɪtɪd/
overexcites	/ˌoʊvɝɛkˈsaɪts/
overexciting	/ˌoʊvɝɛkˈsaɪtɪŋ/
overexpansion	/ˌoʊvɝɪkˈspænʃən/
overexpose	/ˌoʊvɝɪkˈspoʊz/
overexposed	/ˌoʊvɝɪkˈspoʊzd/
overexposes	/ˌoʊvɝɪkˈspoʊzɪz/
overexposing	/ˌoʊvɝɪkˈspoʊzɪŋ/
overexposure	/ˌoʊvɝɪkˈspoʊʒɝ/
overextend	/ˌoʊvɝɪkˈstɛnd/
overextended	/ˌoʊvɝɪkˈstɛndɪd/
overextending	/ˌoʊvɝɪkˈstɛndɪŋ/
overextends	/ˌoʊvɝɪkˈstɛndz/
overfed	/ˌoʊvɝˈfɛd/
overfeed	/ˌoʊvɝˈfid/
overflowed	/ˌoʊvɝˈfɫoʊd/
overfly	/ˌoʊvɝˈfɫaɪ/
overflying	/ˌoʊvɝˈfɫaɪɪŋ/
overgrowing	/ˌoʊvɝˈɡɹoʊwɪŋ/
overgrown	/ˌoʊvɝˈɡɹoʊn/
overhearing	/ˌoʊvɝˈhiɹɪŋ/
overjoyed	/ˌoʊvɝˈdʒɔɪd/
overlying	/ˌoʊvɝˈɫaɪɪŋ/
overmatch	/ˌoʊvɝˈmætʃ/
overnighter	/ˌoʊvɝˈnaɪtɝ/
overnighters	/ˌoʊvɝˈnaɪtɝz/
overoptimism	/ˌoʊvɝˈɑptɪˌmɪzəm/
overpopulate	/ˌoʊvɝˈpɑpjəɫeɪt/
overpopulated	/ˌoʊvɝˈpɑpjəɫeɪtɪd/
overpopulates	/ˌoʊvɝˈpɑpjəɫeɪts/
overpopulating	/ˌoʊvɝˈpɑpjəɫeɪtɪŋ/
overpopulation	/ˌoʊvɝˌpɑpjəˈɫeɪʃən/
overpower	/ˌoʊvɝˈpaʊɝ/
overpowered	/ˌoʊvɝˈpaʊɝd/
overpowers	/ˌoʊvɝˈpaʊɝz/
overprice	/ˌoʊvɝˈpɹaɪs/
overprices	/ˌoʊvɝˈpɹaɪsɪz/
overpricing	/ˌoʊvɝˈpɹaɪsɪŋ/
overproducing	/ˌoʊvɝpɹədˈjusɪŋ/
overprotect	/ˌoʊvɝpɹəˈtɛkt/
overprotected	/ˌoʊvɝpɹəˈtɛktɪd/
overprotection	/ˌoʊvɝpɹəˈtɛkʃən/
overprotective	/ˌoʊvɝpɹəˈtɛktəv/
overrate	/ˌoʊvɝˈɹeɪt/
overrated	/ˌoʊvɝˈɹeɪtɪd/
overrates	/ˌoʊvɝˈɹeɪts/
overrating	/ˌoʊvɝˈɹeɪtɪŋ/
overregulated	/ˌoʊvɝˈɹɛɡjəˌɫeɪtɪd/
overregulation	/ˌoʊvɝˌɹɛɡjəˈɫeɪʃən/
overruled	/ˌoʊvɝˈɹuɫd/
oversea	/ˌoʊvɝˈsi/
overseers	/ˌoʊvɝˈsiɝz/
oversensitive	/ˌoʊvɝˈsɛnsətɪv/
oversensitivity	/ˌoʊvɝsɛnsəˈtɪvɪti/
overshadowed	/ˌoʊvɝˈʃædoʊd/
oversize	/ˌoʊvɝˈsaɪz/
oversizes	/ˌoʊvɝˈsaɪzɪz/
oversizing	/ˌoʊvɝˈsaɪzɪŋ/
oversleep	/ˌoʊvɝˈsɫip/
overslept	/ˌoʊvɝˈsɫɛpt/
overstay	/ˌoʊvɝˈsteɪ/
overstayed	/ˌoʊvɝˈsteɪd/
oversubscribe	/ˌoʊvɝsəbsˈkɹaɪb/
oversubscribed	/ˌoʊvɝsəbsˈkɹaɪbd/
oversupplied	/ˌoʊvɝsəˈpɫaɪd/
oversupply	/ˌoʊvɝsəˈpɫaɪ/
overtaxed	/ˌoʊvɝˈtækst/
overthrew	/ˌoʊvɝˈθɹu/
overthrown	/ˌoʊvɝˈθɹoʊn/
overtook	/ˌoʊvɝˈtʊk/
overuse	/ˌoʊvɝˈjuz/
overused	/ˌoʊvɝˈjuzd/
overuses	/ˌoʊvɝˈjuzɪz/
overusing	/ˌoʊvɝˈjuzɪŋ/
overvaluation	/ˌoʊvɝˌvæɫjuˈeɪʃən/
overweight	/ˌoʊvɝˈweɪt/
overweighted	/ˌoʊvɝˈweɪtɪd/
overwhelm	/ˌoʊvɝˈwɛɫm/, /ˌoʊvɝhˈwɛɫm/
overwhelmability	/ˌoʊvɝˈwɛɫməˈbɪɫəti/, /ˌoʊvɝhwɛɫməˈbɪɫəti/
overwhelmed	/ˌoʊvɝˈwɛɫmd/, /ˌoʊvɝhˈwɛɫmd/
overwhelming	/ˌoʊvɝˈwɛɫmɪŋ/, /ˌoʊvɝhˈwɛɫmɪŋ/
overwhelmingly	/ˌoʊvɝˈwɛɫmɪŋɫi/, /ˌoʊvɝhˈwɛɫmɪŋɫi/
overwhelms	/ˌoʊvɝˈwɛɫmz/, /ˌoʊvɝhˈwɛɫmz/
overwinter	/ˌoʊvɝˈwɪntɝ/
overwork	/ˌoʊvɝˈwɝk/
overworked	/ˌoʊvɝˈwɝkt/
overworking	/ˌoʊvɝˈwɝkɪŋ/
overworks	/ˌoʊvɝˈwɝks/
overwrite	/ˌoʊvɝˈɹaɪt/
overwrites	/ˌoʊvɝˈɹaɪts/
overwriting	/ˌoʊvɝˈɹaɪtɪŋ/
overwritten	/ˌoʊvɝˈɹɪtən/
overwrote	/ˌoʊvɝˈɹoʊt/
overwrought	/ˌoʊvɝˈɹɔt/
overzealous	/ˌoʊvɝˈzɛɫəs/
overzealously	/ˌoʊvɝˈzɛɫəsɫi/
<!-- ovulation	/ˌoʊvjəˈɫeɪʃən/ -->
<!-- ovulations	/ˌoʊvjəˈɫeɪʃənz/ -->
