harmonic	/hɑɹˈmɑnɪk/
harmonica	/hɑɹˈmɑnɪkə/
harmonics	/hɑɹˈmɑnɪks/
harmonious	/hɑɹˈmoʊniəs/
harmoniously	/hɑɹˈmoʊniəsɫi/
harmonium	/hɑɹˈmoʊniəm/
harpoon	/hɑɹˈpun/
harpoons	/hɑɹˈpunz/
<!-- homologous	/hɑˈmɑɫəɡəs/ -->
honduran	/hɑnˈdʊɹən/
hondurans	/hɑnˈdʊɹənz/
honduras	/hɑnˈdʊɹəs/
hostile	/ˈhɑstəɫ/, /hɑˈstaɪɫ/
hostilities	/hɑˈstɪɫətiz/
hostility	/hɑˈstɪɫəti/

haas	/ˈhɑs/
hallmark	/ˈhɑɫˌmɑɹk/
han	/ˈhæn/, /ˈhɑn/
han's	/ˈhænz/, /ˈhɑnz/
hanukkah	/ˈhɑnəkə/
hanukkah's	/ˈhɑnəkəz/
hanukkahs	/ˈhɑnəkəz/
harbin	/ˈhɑɹbɪn/
harbinger	/ˈhɑɹbɪndʒɝ/
harbingers	/ˈhɑɹbɪŋɝz/
harbor	/ˈhɑɹbɝ/
harbor's	/ˈhɑɹbɝz/
harbored	/ˈhɑɹbɝd/
harboring	/ˈhɑɹbɝɪŋ/
harbors	/ˈhɑɹbɝz/
harborside	/ˈhɑɹbɝˌsaɪd/
harbour	/ˈhɑɹbɝ/
harbury	/ˈhɑɹbɝi/
hard	/ˈhɑɹd/
hardback	/ˈhɑɹdˌbæk/
hardball	/ˈhɑɹdˌbɔɫ/
hardboard	/ˈhɑɹdˌbɔɹd/
hardcore	/ˈhɑɹdˈkɔɹ/
hardcover	/ˈhɑɹdˌkəvɝ/
hardcovers	/ˈhɑɹdˌkəvɝz/
hardebeck	/ˈhɑɹdbɛk/
hardee	/ˈhɑɹˈdi/
hardee's	/ˈhɑɹˈdiz/
harden	/ˈhɑɹdən/
harden's	/ˈhɑɹdənz/
hardened	/ˈhɑɹdənd/
hardener	/ˈhɑɹdənɝ/
hardeners	/ˈhɑɹdənɝz/
hardening	/ˈhɑɹdənɪŋ/, /ˈhɑɹdnɪŋ/
hardens	/ˈhɑɹdənz/
harder	/ˈhɑɹdɝ/
hardest	/ˈhɑɹdəst/
hardesty	/ˈhɑɹdəsti/
hardhead	/ˈhɑɹdˌhɛd/
hardheaded	/ˈhɑɹdˌhɛdɪd/
hardier	/ˈhɑɹdiɝ/
hardiest	/ˈhɑɹdiəst/
harding	/ˈhɑɹdɪŋ/
harding's	/ˈhɑɹdɪŋs/
hardliner	/ˈhɑɹdˌɫaɪnɝ/
hardliners	/ˈhɑɹdˌɫaɪnɝz/
hardly	/ˈhɑɹdɫi/
hardness	/ˈhɑɹdnəs/
hardpressed	/ˈhɑɹdˌpɹɛst/
hardscrabble	/ˈhɑɹdsˌkɹæbəɫ/
hardship	/ˈhɑɹdʃɪp/
hardships	/ˈhɑɹdʃɪps/
hardware	/ˈhɑɹdˌwɛɹ/
hardwood	/ˈhɑɹdˌwʊd/
hardwoods	/ˈhɑɹdˌwʊdz/
hardworking	/ˈhɑɹdˌwɝkɪŋ/
hardy	/ˈhɑɹdi/
hark	/ˈhɑɹk/
harken	/ˈhɑɹkən/
harkens	/ˈhɑɹkənz/
harking	/ˈhɑɹkɪŋ/
harks	/ˈhɑɹks/
harlem	/ˈhɑɹɫəm/
harlem's	/ˈhɑɹɫəmz/
harlequin	/ˈhɑɹɫəkwən/
harley	/ˈhɑɹɫi/
harley's	/ˈhɑɹɫiz/
harlot	/ˈhɑɹɫət/
harlow	/ˈhɑɹɫoʊ/
harm	/ˈhɑɹm/
harm's	/ˈhɑɹmz/
harmed	/ˈhɑɹmd/
harmen	/ˈhɑɹmən/
harmer	/ˈhɑɹmɝ/
harmful	/ˈhɑɹmfəɫ/
harmfully	/ˈhɑɹmfəɫi/
harmfulness	/ˈhɑɹmfəɫnəs/
harming	/ˈhɑɹmɪŋ/
harmless	/ˈhɑɹmɫəs/
harmlessly	/ˈhɑɹmɫəsɫi/
harmon	/ˈhɑɹmən/
harmon's	/ˈhɑɹmənz/
harmonies	/ˈhɑɹməniz/
harmonize	/ˈhɑɹməˌnaɪz/
harmonized	/ˈhɑɹməˌnaɪzd/
harmonizes	/ˈhɑɹməˌnaɪzɪz/
harmonizing	/ˈhɑɹməˌnaɪzɪŋ/
harmony	/ˈhɑɹməni/
harms	/ˈhɑɹmz/
harness	/ˈhɑɹnəs/, /ˈhɑɹnɪs/
harnessed	/ˈhɑɹnəst/
harnesses	/ˈhɑɹnəsəz/, /ˈhɑɹnəsɪz/
harnessing	/ˈhɑɹnəsɪŋ/
harp	/ˈhɑɹp/
harped	/ˈhɑɹpt/
harper	/ˈhɑɹpɝ/
harper's	/ˈhɑɹpɝz/
harpercollins	/ˈhɑɹpɝˈkɔɫɪnz/
harpers	/ˈhɑɹpɝz/
harping	/ˈhɑɹpɪŋ/
harpist	/ˈhɑɹpɪst/
harpists	/ˈhɑɹpɪsts/
harps	/ˈhɑɹps/
harpsichord	/ˈhɑɹpsəˌkɔɹd/
harsh	/ˈhɑɹʃ/
harsher	/ˈhɑɹʃɝ/
harshest	/ˈhɑɹʃəst/
harshly	/ˈhɑɹʃɫi/
harshness	/ˈhɑɹʃnəs/
harvard	/ˈhɑɹvɝd/
harvard's	/ˈhɑɹvɝdz/
harvest	/ˈhɑɹvəst/
harvestable	/ˈhɑɹvəstəbəɫ/
harvested	/ˈhɑɹvəstɪd/
harvester	/ˈhɑɹvəstɝ/
harvesters	/ˈhɑɹvəstɝz/
harvesting	/ˈhɑɹvəstɪŋ/
harvests	/ˈhɑɹvəsts/
harvey	/ˈhɑɹvi/
harvey's	/ˈhɑɹviz/
heart	/ˈhɑɹt/
heart's	/ˈhɑɹts/
heartache	/ˈhɑɹˌteɪk/
heartbeat	/ˈhɑɹtˌbit/
heartbeats	/ˈhɑɹtˌbits/
heartbreak	/ˈhɑɹtˌbɹeɪk/
heartbreaking	/ˈhɑɹtˌbɹeɪkɪŋ/
heartbreaks	/ˈhɑɹtˌbɹeɪks/
heartbroken	/ˈhɑɹtˌbɹoʊkən/
heartburn	/ˈhɑɹtˌbɝn/
hearted	/ˈhɑɹtəd/, /ˈhɑɹtɪd/
heartedly	/ˈhɑɹtɪdɫi/
hearten	/ˈhɑɹtən/
heartened	/ˈhɑɹtənd/
heartening	/ˈhɑɹtənɪŋ/, /ˈhɑɹtnɪŋ/
heartfelt	/ˈhɑɹtˌfɛɫt/
hearth	/ˈhɑɹθ/
hearths	/ˈhɑɹθs/
heartier	/ˈhɑɹtiɝ/
heartiest	/ˈhɑɹtiəst/
heartily	/ˈhɑɹtəɫi/
heartland	/ˈhɑɹtˌɫænd/
heartless	/ˈhɑɹtɫəs/
hearts	/ˈhɑɹts/
heartscan	/ˈhɑɹtˌskæn/
heartthrob	/ˈhɑɹtˌθɹɑb/
heartthrobs	/ˈhɑɹtˌθɹɑbz/
heartwarming	/ˈhɑɹtˌwɔɹmɪŋ/
heartwise	/ˈhɑɹtˌwaɪz/
heartwood	/ˈhɑɹtˌwʊd/
hearty	/ˈhɑɹti/
hob	/ˈhɑb/
hobbes	/ˈhɑbiz/, /ˈhɑbz/
hobbies	/ˈhɑbiz/
hobbit	/ˈhɑbɪt/
hobble	/ˈhɑbəɫ/
hobbled	/ˈhɑbəɫd/
hobbles	/ˈhɑbəɫz/
hobbling	/ˈhɑbəɫɪŋ/, /ˈhɑbɫɪŋ/
hobby	/ˈhɑbi/
hobbyist	/ˈhɑbiɪst/
hobbyists	/ˈhɑbiɪsts/
hobnail	/ˈhɑbˌneɪɫ/
hobnob	/ˈhɑbˌnɑb/
hobnobbing	/ˈhɑbˌnɑbɪŋ/
hobs	/ˈhɑbz/
hoc	/ˈhɑk/
hock	/ˈhɑk/
hocker	/ˈhɑkɝ/
hockey	/ˈhɑki/
hockey's	/ˈhɑkiz/
hocking	/ˈhɑkɪŋ/
hockney	/ˈhɑkni/
hockney's	/ˈhɑkniz/
hodge	/ˈhɑdʒ/
hodge's	/ˈhɑdʒɪz/
hodgepodge	/ˈhɑdʒˌpɑdʒ/
hodges	/ˈhɑdʒɪz/
hodgkin	/ˈhɑdʒkɪn/
hodgkin's	/ˈhɑdʒkɪnz/
hodgkins	/ˈhɑdʒkɪnz/
hodgkinson	/ˈhɑdʒkɪnsən/
hog	/ˈhɑɡ/
hogg	/ˈhɑɡ/
hognose	/ˈhɑɡˌnoʊz/
hogs	/ˈhɑɡz/
hogwarts	/ˈhɑˌɡwɔɹts/
hogwash	/ˈhɑˌɡwɑʃ/
holiday	/ˈhɑɫəˌdeɪ/, /ˈhɑɫɪˌdeɪ/
holiday's	/ˈhɑɫəˌdeɪz/
holidays	/ˈhɑɫəˌdeɪz/
holland	/ˈhɑɫənd/
holland's	/ˈhɑɫəndz/
hollander	/ˈhɑɫəndɝ/
hollanders	/ˈhɑɫəndɝz/
hollands	/ˈhɑɫəndz/
holley	/ˈhɑɫi/
hollow	/ˈhɑɫoʊ/
hollow's	/ˈhɑɫoʊz/
holloway	/ˈhɑɫoʊˌweɪ/
hollowed	/ˈhɑɫoʊd/
hollowing	/ˈhɑɫoʊɪŋ/
hollows	/ˈhɑɫoʊz/
holly	/ˈhɑɫi/
holly's	/ˈhɑɫiz/
hollyhock	/ˈhɑɫiˌhɑk/
hollyhocks	/ˈhɑɫiˌhɑks/
hollywood	/ˈhɑɫiˌwʊd/
hollywood's	/ˈhɑɫiˌwʊdz/
holman	/ˈhɑɫmən/
holocaust	/ˈhɑɫəˌkɔst/
hologram	/ˈhɑɫəˌɡɹæm/
holograms	/ˈhɑɫəˌɡɹæmz/
<!-- homage	/ˈɑmədʒ/, /ˈhɑmədʒ/ -->
<!-- homages	/ˈɑmədʒəz/, /ˈhɑmədʒəz/ -->
<!-- hombre	/ˈhɑmbɹə/ -->
homburg	/ˈhɑmbɝɡ/
homicide	/ˈhɑməˌsaɪd/
homicides	/ˈhɑməˌsaɪdz/
homily	/ˈhɑməɫi/
hominem	/ˈhɑmɪnɛm/
hominid	/ˈhɑmənɪd/
hominy	/ˈhɑmɪni/
homs	/ˈhɑmz/
<!-- honda's	/ˈhɑndəz/ -->
<!-- hondas	/ˈhɑndəs/ -->
honk	/ˈhɑŋk/, /ˈhɔŋk/
honnold	/ˈhɑˌnoʊɫd/
hopkin	/ˈhɑpkɪn/
hopkin's	/ˈhɑpkɪnz/
hopkins	/ˈhɑpkɪnz/
hopkins'	/ˈhɑpkɪnz/
hopped	/ˈhɑpt/
hopper	/ˈhɑpɝ/
hopper's	/ˈhɑpɝz/
hoppers	/ˈhɑpɝz/
hopping	/ˈhɑpɪŋ/
hopple	/ˈhɑpəɫ/
hops	/ˈhɑps/
hopscotch	/ˈhɑpˌskɑtʃ/
hopscotched	/ˈhɑpˌskɑtʃt/
hospice	/ˈhɑspəs/
hospice's	/ˈhɑspəsɪz/
hospices	/ˈhɑspəsɪz/
hospitable	/ˈhɑˈspɪtəbəɫ/
hospital	/ˈhɑˌspɪtəɫ/
hospital's	/ˈhɑˌspɪtəɫz/
hospitalized	/ˈhɑspɪtəˌɫaɪzd/
hospitals	/ˈhɑˌspɪtəɫz/
hostage	/ˈhɑstɪdʒ/
hostages	/ˈhɑstədʒəz/
hostel	/ˈhɑstəɫ/
hostels	/ˈhɑstəɫz/
hostile	/ˈhɑstəɫ/, /hɑˈstaɪɫ/
hostler	/ˈhɑsɫɝ/
hot	/ˈhɑt/
hot-cross	/ˈhɑtˈkɹɔs/
hot-line	/ˈhɑtˈɫaɪn/
hot-shot	/ˈhɑˌʃɑt/
hot-shots	/ˈhɑˌʃɑts/
hotbed	/ˈhɑtˌbɛd/
hotbeds	/ˈhɑtˌbɛdz/
hotcake	/ˈhɑtˌkeɪk/
hotcakes	/ˈhɑtˌkeɪks/
hotdog	/ˈhɑtˌdɔɡ/
hotdogs	/ˈhɑtˌdɔɡz/
hothouse	/ˈhɑtˌhaʊs/
hothouses	/ˈhɑtˌhaʊsɪz/
hotline	/ˈhɑtˌɫaɪn/
hotlines	/ˈhɑtˌɫaɪnz/
hotly	/ˈhɑtɫi/
hotmail	/ˈhɑtˌmeɪɫ/
hotpot	/ˈhɑtˌpɔt/
hots	/ˈhɑts/
hotshot	/ˈhɑˌʃɑt/
hotshots	/ˈhɑˌʃɑts/
hotspot	/ˈhɑtˌspɑt/
hotter	/ˈhɑtɝ/
hottest	/ˈhɑtəst/
hotz	/ˈhɑts/
<!-- khalid	/ˈhɑɫɪd/, /ˈkɑɫɪd/ -->
<!-- khalid's	/ˈhɑɫɪdz/, /ˈkɑɫɪdz/ -->

ha-ha	/ˌhɑˈhɑ/
ha-ha-ha	/ˌhɑˌhɑˈhɑ/
<!-- hamas	/ˌhɑˈmɑs/ -->
<!-- hamas'	/ˌhɑˈmɑs/ -->
hard-ass	/ˌhɑɹˌdæs/
hard-working	/ˌhɑɹdhˈwɝkɪŋ/
hardwired	/ˌhɑɹdˈwaɪɝd/
harmonization	/ˌhɑɹmənɪˈzeɪʃən/
holographic	/ˌhɑɫəˈɡɹæfɪk/
homicidal	/ˌhɑməˈsaɪdəɫ/
homiletic	/ˌhɑməˈɫɛtɪk/
homogeneity	/ˌhɑmədʒəˈniəti/
honolulu	/ˌhɑnəˈɫuɫu/
honolulu's	/ˌhɑnəˈɫuɫuz/
hospitality	/ˌhɑspəˈtæɫəti/
hospitalization	/ˌhɑspɪtəɫəˈzeɪʃən/
hospitalizations	/ˌhɑspɪtəɫəˈzeɪʃənz/
javier	/ˌhɑviˈɛɹ/
